Modernize the codebase
arturbac/kdevcxx_with_ai pull request #11
Opened 2024-12-29 22:56 UTC by Petross404

This PR applies the `default` keywords to empty dtors, `Q_DISABLE_COPY_MOVE` macro to specifically delete any move or copy operation, const qualifies some variables and functions etc.

2025-01-15 19:05 UTC, arturbac requested changes
I am not allowed to apply clang-format, so do it Yourself pls or let me push into PR.

2025-01-16 07:54 UTC, Petross404 commented
> I am not allowed to apply clang-format, so do it Yourself pls or let me push into PR.

I am happy to help. Should I format the changed files only and run `git commit --amend --no-edit`?

2025-01-16 09:59 UTC, arturbac commented
nvm Ill reformat code later.

2025-01-16 09:59 UTC, arturbac commented
could You enable allow edit for me in PR, it is in Your options

2025-01-16 10:13 UTC, Petross404 commented
![image](https://github.com/user-attachments/assets/7e0b82a8-237f-4496-b53b-6f5995f9131e)

Like this?

2025-01-16 13:26 UTC, arturbac commented
> Like this?
sure thx.
Btw I do not like "pedantic" const correctness on everything, I never make errors "use after move" but it very often causes prevention of copy elision. Sometimes for complex code I use const when I explicitly want to know variable was not modified but not in such approach as in this PR, this is redundant and makes code less readable and possibly prevents copy elision for named variables if applicable.
Anyway it does nothing valuable in this code, but since You did that just make sure there is no such case when const named variable is returned from function and previously it was not const.

2025-01-16 18:19 UTC, Petross404 commented
> Anyway it does nothing valuable in this code, but since You did that just make sure there is no such case when const named variable is returned from function and previously it was not const.

I suspect the compiler would rant about it? I might got carried away from clang-tidy's proposals and best practices. Whatever, I can remove them, it's not like it's *the* improvement or something.

2025-10-15 17:23 UTC, closed without merging